on:
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    - name: Unit tests
      uses: actions/checkout@v2
    - run: docker-compose -f docker-compose.yml.dist pull
    - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
    - name: Prepare containers
      run: make run && make prepare
    - name: Run tests
      run: make tests
